### ISSUE TITLE
Error: bash: line 1: 1999 Killed:

### ISSUE THREAD

**Issue by volkan0x** [Angelmaneuver/remember-the-milk.widget#3] opened 2023-10-13 08:44 UTC
I got an error when trying to launc the widget:

We got an error: Error: bash: line 1: 1999 Killed: 9 ./task-deadline.widget/bin/rtm-cli getFrob

**Comment by Angelmaneuver** [comment] 2023-10-14 22:48
Hi volfcan.
I'll answer for your issue.

Sorry, we were not able to determine the cause of the problem or how to address it from what you described.
This is because I cannot reproduce it in my environment.

We need information from you for our investigation (Mac environment etc…).

If there are no additional informations, I'll close this issue in about week.

**Comment by volkan0x** [comment] 2023-10-15 18:00
I simply launch the app and activated the widget and got an error.
<img width="915" alt="Screenshot 2023-10-15 at 20 59 00" src="https://github.com/Angelmaneuver/task-deadline-with-rtm/assets/68243739/3e16ff76-a9bd-4af0-abfe-2c94a0961285">

**Comment by Angelmaneuver** [comment] 2023-10-15 18:16
I am sorry, but I am unable to reproduce the problem because it is working fine on my device and I have decided that I cannot deal with it based on the information you have provided.

I am sorry, but you will have to give up using this widget.

**Closed as completed by Angelmaneuver** 2023-10-15 18:16 UTC
